jobs:
  build:
    name: build-and-testing
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Rate limit info
      run: 'curl -H "Accept: application/vnd.github+json" https://api.github.com/rate_limit'
    - continue-on-error: true
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled
        }}
      name: Setup tmate session
      uses: mxschmitt/action-tmate@a283f9441d2d96eb62436dc46d7014f5d357ac22
      with:
        limit-access-to-actor: true
    - continue-on-error: true
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4
    - continue-on-error: true
      name: install-java8
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: build-gradle
      run: ./gradlew --no-daemon clean build installDist publish --build-cache --scan
        -s
    - continue-on-error: true
      if: runner.os != 'Windows'
      name: integration-test-non-windows
      run: 'export PATH=`pwd`/build/install/jbang/bin:$PATH

        cd itests

        ./test_suite.sh

        ./itests.sh

        '
    - continue-on-error: true
      name: add-to-path
      run: echo "../build/install/jbang/bin" >> $env:GITHUB_PATH
    - continue-on-error: true
      if: runner.os == 'Windows'
      name: integration-test-windows
      run: "echo \"::add-matcher::.github/karatewindows-matcher.json\" \n.\\itests.cmd\n\
        echo \"::remove-matcher owner=karate-windows::\"\n"
      working-directory: itests
    - continue-on-error: true
      name: codecoverage-report
      run: './gradlew --no-daemon jacocoTestReport

        '
    - continue-on-error: true
      if: always()
      name: Upload Test Report
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: junit-test-results
        path: '**/build/test-results/test/TEST-*.xml'
        retention-days: 1
    - continue-on-error: true
      uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b
      with:
        flags: ${{ runner.os }}
        name: ${{ runner.os }}-tests
        verbose: true
    - continue-on-error: true
      if: runner.os == 'Windows'
      name: build-choco-package
      uses: actions/setup-dotnet@608ee757cfcce72c2e91e99aca128e0cae67de87
      with:
        dotnet-version: 2.2.204
    - continue-on-error: true
      if: runner.os == 'Windows'
      name: build-choco
      run: 'powershell

        choco pack build/choco/jbang.nuspec

        '
    - continue-on-error: true
      if: always()
      name: Archive build results
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: ${{ runner.os }}-build-${{ github.sha }}
        path: build
    - continue-on-error: true
      if: always() && runner.os != 'Windows'
      name: Upload jbang.zip
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: jbang-${{ github.sha }}
        path: build/install/jbang
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
  testing:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
      with:
        name: ${{ runner.os }}-build-${{ github.sha }}
        path: build
    - continue-on-error: true
      name: smoke-test
      run: 'java -version

        chmod +x ./build/install/jbang/bin/jbang

        ./build/install/jbang/bin/jbang init --template=cli helloworld.java

        ./build/install/jbang/bin/jbang --verbose helloworld.java

        rm helloworld.java

        '
    - continue-on-error: true
      name: smoke-quarkus-test
      run: 'java -version

        chmod +x ./build/install/jbang/bin/jbang

        ./build/install/jbang/bin/jbang init --template=qcli qcli.java

        ./build/install/jbang/bin/jbang --fresh --verbose qcli.java

        rm qcli.java

        '
    - continue-on-error: true
      name: smoke-quarkus-diff-version-test
      run: 'java -version

        chmod +x ./build/install/jbang/bin/jbang

        ./build/install/jbang/bin/jbang init --template=qcli qcli.java

        ./build/install/jbang/bin/jbang --fresh --verbose --java 17 qcli.java

        rm qcli.java

        '
    - continue-on-error: true
      if: runner.os != 'Windows' && matrix.java < 17
      name: integration-test-non-windows
      run: 'export PATH=`pwd`/build/install/jbang/bin:$PATH

        cd build/itests

        chmod +x ./test_suite.sh

        chmod +x ./itests.sh

        ./test_suite.sh

        ./itests.sh

        '
    - continue-on-error: true
      name: add-to-path
      run: echo "../build/install/jbang/bin" >> $env:GITHUB_PATH
    - continue-on-error: true
      if: runner.os == 'Windows' && matrix.java < 17
      name: integration-test-windows
      run: "echo \"::add-matcher::.github/karatewindows-matcher.json\" \n.\\itests.cmd\n\
        echo \"::remove-matcher owner=karate-windows::\"\n"
      working-directory: itests
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        - 19
        os:
        - ubuntu-latest
  updatewebsite:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      with:
        fetch-depth: 2
    - continue-on-error: true
      id: verify-changed-files
      name: Verify Changed files in docs
      uses: tj-actions/verify-changed-files@fda469d6b456070da68fa3fdbc07a513d858b200
      with:
        files: 'docs

          '
    - continue-on-error: true
      if: ${{ github.ref == 'refs/heads/main' && steps.verify-changed-files.outputs.files_changed
        == 'true'}}
      name: update website
      uses: benc-uk/workflow-dispatch@25b02cc069be46d637e8fe2f1e8484008e9e9609
      with:
        repo: jbangdev/jbang.dev
        token: ${{ secrets.BREW_GITHUB_TOKEN }}
        workflow: github-pages
name: ci-build
on:
  repository_dispatch:
    types: trigger-ga___ci-build.yml
