jobs:
  checks:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download Test Report
      uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e
      with:
        name: junit-test-results
        run_id: ${{ github.event.workflow_run.id }}
        workflow: ${{ github.event.workflow.id }}
    - continue-on-error: true
      name: Publish Test Report
      uses: mikepenz/action-junit-report@150e2f992e4fad1379da2056d1d1c279f520e058
      with:
        commit: ${{github.event.workflow_run.head_sha}}
        report_paths: '**/build/test-results/test/TEST-*.xml'
name: report
on:
  repository_dispatch:
    types: trigger-ga___report.yml
permissions:
  checks: write
