jobs:
  build:
    env:
      JRELEASER_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      JRELEASER_NEXUS2_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      JRELEASER_NEXUS2_USERNAME: ${{ secrets.OSSRH_USERNAME}}
      JRELEASER_SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
      JRELEASER_SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
      JRELEASER_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      JRELEASER_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET
        }}
      JRELEASER_TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      JRELEASER_TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      JRELEASER_VERSION: 1.5.1
    name: build-and-testing
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: install-java11
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: build-gradle
      run: ./gradlew --no-daemon clean build installDist publish --build-cache --scan
        -s
    - continue-on-error: true
      name: integration-test
      run: 'export PATH=`pwd`/build/install/jbang/bin:$PATH

        pastdir=`pwd`

        cd itests

        ./test_suite.sh

        ./itests.sh

        cd $pastdir

        '
    - continue-on-error: true
      id: version
      name: version extract
      run: 'RELEASE_VERSION=`cat build/tmp/version.txt`

        echo "::set-output name=RELEASE_VERSION::$RELEASE_VERSION"

        '
    - continue-on-error: true
      env:
        JRELEASER_PROJECT_VERSION: ${{steps.version.outputs.RELEASE_VERSION}}
      name: Run JReleaser
      uses: jreleaser/release-action@v2
      with:
        arguments: release
        setup-java: false
        version: ${{ env.JRELEASER_VERSION }}
    - continue-on-error: true
      if: always()
      name: JReleaser output
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: jreleaser-release
        path: 'out/jreleaser/trace.log

          out/jreleaser/output.properties

          '
name: tag-and-release
on:
  repository_dispatch:
    types: trigger-ga___tag-and-release.yml
